[build]
  command = "npm run build"
  publish = "src/.next"
  base = ""  # keep root as base, not src

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["next", "react", "react-dom"]
