[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"
  version = "5.14.0"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["next", "react", "react-dom"]
