[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NETLIFY_NEXT_PLUGIN_SKIP_FUNCTION_BUNDLING = "true"
  NETLIFY_USE_LEGACY_NEXT_PLUGIN = "true"
