[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  included_files = [
    "src/**/*",
    "public/**/*",
    ".env",
    ".env.production",
    ".env.local",
    ".env.production.local"
  ]

# Optional performance headers
[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Your redirect rules (already in public/_redirects)
# Netlify will automatically read them from /public/_redirects
