[build]
  command = "npm run build"
  publish = ".next"
  base = "src"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["next", "react", "react-dom"]
