[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  node_bundler = "esbuild"
  included_files = ["src/**/*", "public/**/*"]
  external_node_modules = ["next", "react", "react-dom", "sharp"]
  included_files_base = "."

[build.environment]
  NETLIFY_NEXT_PLUGIN_SKIP_FUNCTION_BUNDLING = "true"
